<?php
echo '<html>';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<title>Pagina</title>';
echo '<style>';
echo 'p{
  font-size:2.1em; 

}
';
echo '</style>';

echo'<link rel="stylesheet" type="text/css" href="css/style2.css">';
echo '</head>';
echo '<body class="cuerpo" background="image/gris.jpeg"  >';


echo '<ul id="menu" size="30">';
echo'<li><a font color="white"  class="prueba">Pagina de prueba</a>';

echo '&nbsp';echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '&nbsp';
echo '<input style="font-size:15px" class="email" type="text" name="email" placeholder="&nbsp email" size="18 " >';
echo '&nbsp';
echo '&nbsp';
echo '<input style="font-size:15px" class="contraseña" type="text" name="contraseña" placeholder="&nbsp contraseña"  size="18 ">';
echo '&nbsp';
echo '&nbsp';
echo '<input style="font-size:14px"  class="ingresar" type="submit" name="ingresar" value="Ingresar" size="28"> ';
echo'</li>';
echo '</ul>';
echo '<center><h1 style="font-size:60px" class="lorem" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lorem ipsum dolor sit  amet,consetetur<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;adipiscing elit.</h1></center>';

echo '<center><p style="font-size:21px" class="parrafo">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;lorem ipsum dolor sit amet,consectetur adipiscing elit.Aenean autor vitae auge eu omare .Lorem ipsum dolor sit amet<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;consectetur adipiscing elit..morbit sit amet ante nec neque cogue vulputate sit amet ac doctor.Duis eu quam libero.Etiam<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; id nunc at elementum .Nulian vitae orci aliquam lobortis nulla in ,consectur leo.Ut eu dolor quis risus vehicula<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;faicibus ac  convalls sapien.Nulla portitlo ipsum vitae maximus euismod,metus lectus euismod ex,ac bibendum erat<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mauris sit amet magna .Donec lacinia omare molestie.Cras ac euismod dolor .Mauris volutpad id arcu vitae ferntum<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nunc tempus faubus autor.Etiam imperdirt eral ex. Maecenas congue eget tellus in scelenrisque.Nulla eu convalls velit<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at rhoncus dui.</p></center>';
echo '<br>';
echo '<br>';

echo '<center><input style="font-size:14px"  class="lea" type="submit" name="lea" value="leam more >>" size="28">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</center>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<br>';
echo '<table class="tabla" >';
echo '<p  style="font-size:25px" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cabecera </p>';
echo '<p  style="font-size:15px" class="donec" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Donec id elitnon mi porta gravia at eget metus.Fusce<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
dapilus,telus ac cursus commondo.torto mauris<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
condimentun nibh,ut fermentu massa justo sit amel<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
risus.Etiam porta sem malesuada magna molls eusmod.<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
Donec sed odio dui.</p>';
echo '</table>';
echo '<br>';


echo '<center><input style="font-size:14px"  class="ingresar" type="submit" name="ingresar" value="View details" size="28">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</center>';

echo '</body>';
echo"</center>";


echo '</html>';
?>